Sapbw 2.0
dyvenia/viadot pull request #1053
Opened 2024-09-25 09:41 UTC by gwieloch

## Summary
SAP BW connector migration from viadot 1 to viadot 2. Also added some utility functions into viadot utils.

## Importance
Required by the migration project.

## Checklist

This PR:
- [x] follows the guidelines laid out in `CONTRIBUTING.md`
- [ ] links relevant issue(s)
- [x] adds/updates tests (if appropriate)
- [x] adds/updates docstrings (if appropriate)
- [x] adds an entry in `CHANGELOG.md`

2024-09-25 13:21 UTC, trymzet commented
@gwieloch it seems the checks are failing, can you make sure they pass first, then request PR review? Otherwise I would need to check the same code twice.

As for the tests failing due to `pyrfc` not being installed, you need to escape this import in the source, tasks, and tests, same as in the SAP RFC source:
https://github.com/dyvenia/viadot/blob/2.0/src/viadot/sources/sap_rfc.py#L19-L24
https://github.com/dyvenia/viadot/blob/2.0/tests/unit/test_sap_rfc.py#L6-L9
https://github.com/dyvenia/viadot/blob/2.0/src/viadot/orchestration/prefect/tasks/sap_rfc.py#L11-L12

For more info, see the "optional dependencies" sections in the developer guide docs https://viadot.docs.dyvenia.com/developer_guide/

2024-09-25 13:23 UTC, trymzet requested changes
Checks not passing

2024-09-27 13:54 UTC, Rafalz13 commented on tests/integration/test_sap_bw.py
> +def test_mindful_to_adls(sap_bw_config_key, adls_credentials_secret):
```suggestion
def test_sap_bw_to_adls(sap_bw_config_key, adls_credentials_secret):
```

2024-09-27 15:02 UTC, trymzet requested changes
Added my comments. Some unit tests should also be added.

2024-09-27 15:02 UTC, trymzet commented on tests/integration/test_sap_bw.py
> +"""'test_sap_bw.py'."""
This should be under orchestration directory.

2024-09-30 07:42 UTC, angelika233 commented on src/viadot/sources/sap_bw.py
> +    def _apply_user_mapping(
issue #1066

2024-09-30 07:42 UTC, angelika233 commented on src/viadot/sources/sap_bw.py
> +        conn.close()
issue #1066

2024-09-30 07:58 UTC, angelika233 commented on src/viadot/sources/sap_bw.py
> +                column names. Defaults to None.
#1066

2024-09-30 08:36 UTC, trymzet commented on src/viadot/sources/sap_bw.py
> +                column names. Defaults to None.
I mean the docstring, lines 160-161. This shouldn't be under the "Raises" section but under Args.

2024-09-30 08:55 UTC, merged