✨ Add DynamicDateHandler class
dyvenia/viadot pull request #1093
Opened 2024-10-14 07:49 UTC by malgorzatagwinner

## Summary
Introducing a class to handle pendulum DateTimes or time-related patterns within a provided text, replacing dynamic date marker with actual dates.

## Importance
To make sure that Prefect 2 recognizes the dynamically changing dates, allowing the team to move on from the hardcoded dates and changing them every year.

## Checklist

This PR:
- [ ] follows the guidelines laid out in `CONTRIBUTING.md`
- [ ] links relevant issue(s)
- [ ] adds/updates tests (if appropriate)
- [ ] adds/updates docstrings (if appropriate)
- [ ] adds an entry in `CHANGELOG.md`

2024-10-14 08:43 UTC, Rafalz13 requested changes
Added some comments.
Please install `pre-commit` to be able to validate the code structure locally.

2024-10-14 08:43 UTC, Rafalz13 commented on src/viadot/orchestration/prefect/utils.py
> +    def generate_years(
mark this function internal by adding `_`.
```suggestion
    def _generate_years(
```

2024-10-14 08:43 UTC, Rafalz13 commented on src/viadot/orchestration/prefect/utils.py
> +    def generate_months(self, last_months: int) -> List[str]:
mark this function internal by adding `_`.
```suggestion
    def _generate_months(self, last_months: int) -> List[str]:
```

2024-10-14 08:43 UTC, Rafalz13 commented on src/viadot/orchestration/prefect/utils.py
> +    def generate_dates(self, last_days: int) -> List[str]:
mark this function internal by adding `_`.
```suggestion
    def _generate_dates(self, last_days: int) -> List[str]:
```

2024-10-14 08:43 UTC, Rafalz13 commented on src/viadot/orchestration/prefect/utils.py
> +    def process_first_days(
mark this function internal by adding `_`.
```suggestion
    def _process_first_days(
```

2024-10-14 08:43 UTC, Rafalz13 commented on src/viadot/orchestration/prefect/utils.py
> +    def process_last_days(self, month_name: str, year: int, num_days: int) -> List[str]:
mark this function internal by adding `_`.
```suggestion
    def _process_last_days(self, month_name: str, year: int, num_days: int) -> List[str]:
```

2024-10-14 08:43 UTC, Rafalz13 commented on src/viadot/orchestration/prefect/utils.py
> +    def process_last_day_of_month(
mark this function internal by adding `_`.
```suggestion
    def _process_last_day_of_month(
```

2024-10-14 08:43 UTC, Rafalz13 commented on src/viadot/orchestration/prefect/utils.py
> +    def process_x_years_ago(self, year: str) -> str:
mark this function internal by adding `_`.
```suggestion
    def _process_x_years_ago(self, year: str) -> str:
```

2024-10-14 08:43 UTC, Rafalz13 commented on src/viadot/orchestration/prefect/utils.py
> +    def get_date_x_ago_full_date(self, number: int, unit: str) -> pendulum.DateTime:
mark this function internal by adding `_`.
```suggestion
    def _get_date_x_ago_full_date(self, number: int, unit: str) -> pendulum.DateTime:
```

2024-10-14 08:43 UTC, Rafalz13 commented on src/viadot/orchestration/prefect/utils.py
> +    def create_date_dict(self) -> Dict[str, str]:
mark this function internal by adding `_`.
```suggestion
    def _create_date_dict(self) -> Dict[str, str]:
```

2024-10-14 08:43 UTC, Rafalz13 commented on src/viadot/orchestration/prefect/utils.py
> +    def handle_singular_dates(self, match: List[tuple], key: str) -> pendulum.DateTime:
mark this function internal by adding `_`.
```suggestion
    def _handle_singular_dates(self, match: List[tuple], key: str) -> pendulum.DateTime:
```

2024-10-14 08:43 UTC, Rafalz13 commented on src/viadot/orchestration/prefect/utils.py
> +    def generate_dates_based_on_unit(self, number: int, unit: str) -> List[str]:
mark this function internal by adding `_`.
```suggestion
    def _generate_dates_based_on_unit(self, number: int, unit: str) -> List[str]:
```

2024-10-14 08:43 UTC, Rafalz13 commented on src/viadot/orchestration/prefect/utils.py
> +    def handle_data_ranges(self, match: List[tuple], key: str) -> List[str]:
mark this function internal by adding `_`.
```suggestion
    def _handle_data_ranges(self, match: List[tuple], key: str) -> List[str]:
```

2024-10-14 08:43 UTC, Rafalz13 commented on src/viadot/orchestration/prefect/utils.py
> +    def recognize_date(self, text: str) -> List[str] | str:
Change the function name to `process_dates` or something similar.

2024-10-14 08:43 UTC, Rafalz13 commented on src/viadot/orchestration/prefect/utils.py
* Replace all patterns and possible inputs from `this year` to `this_year`. Use snake case for all of the cases to have one general pattern for them.
* Change all types `List[]` -> `list[]`, `Dict` -> `dict` to follow the convention that is used in viadot

2024-10-14 08:43 UTC, Rafalz13 commented on src/viadot/orchestration/prefect/utils.py
> +                x = int(x)
You do not need this line. You are parsing the same in the line below

2024-10-14 08:43 UTC, Rafalz13 commented on src/viadot/orchestration/prefect/utils.py
> +                x = int(x)
You can parse it in the line below. If you want to do it here please assign it to the different variable. `x` in used for `for loop`

2024-10-14 08:43 UTC, Rafalz13 commented on src/viadot/orchestration/prefect/utils.py
> +        Returns a list of dynamically created dates generated based on `unit` in an ascending order.
You can move the second line to the `Returns` section.

2024-10-14 08:43 UTC, Rafalz13 commented on src/viadot/orchestration/prefect/utils.py
> +        Returns a pendulum.DateTime date generated based on `match`.
You can move the second line to the `Retuirns` section.

2024-10-14 08:43 UTC, Rafalz13 commented on src/viadot/orchestration/prefect/utils.py
> +        Dictionary values "today", "yesterday" and "last year previous month" are formatted into the dynamic_date_format.
Add blank line between the first and second line or add `# noqa: D205` at the and of the docstring:
```
""" text """ # noqa: D205
```

2024-10-14 08:43 UTC, Rafalz13 commented on src/viadot/orchestration/prefect/utils.py
> +        """
Add `# noqa: D205` at the end. There is an issue with precommit saying that `1 blank line required between summary line and description`
```
""" text """ # noqa: D205
```

2024-10-14 08:43 UTC, Rafalz13 commented on src/viadot/orchestration/prefect/utils.py
> +
You have only if and elif here. Add `return None` or `[]` at the end to be able to return anything if key is different than all listed cases. Check what would be valid here. If return None then add `| None` to the return type.

2024-10-14 08:43 UTC, Rafalz13 commented on src/viadot/orchestration/prefect/utils.py
> +
You have only if and elif here. Add `return None` or `[]` at the end to be able to return anything if key is different than all listed cases. Check what would be valid here. If `return None` will be added then add `| None` to the return type.

2024-10-29 12:02 UTC, Rafalz13 reviewed
Looks good, but lacks testing.

2024-10-31 15:58 UTC, trymzet requested changes

2024-10-31 15:58 UTC, trymzet commented on tests/unit/orchestration/prefect/test_utils.py
> +    expected_text = f"The year is {setup_dates['today'][:4]}."
```suggestion
    expected_text = f"The year is {setup_dates['current_year']}."
```

2024-10-31 15:58 UTC, trymzet commented on tests/unit/orchestration/prefect/test_utils.py
> +
This doesn't test anything new so I'd just remove it.
```suggestion
```

2024-10-31 15:58 UTC, trymzet commented on tests/unit/orchestration/prefect/test_utils.py
> +def test_Y_years_from_x():
It's easier to read if you use the same naming convention as in your other tests
```suggestion
def test_process_y_years_from_x():
```

2024-11-04 11:04 UTC, Rafalz13 commented on src/viadot/orchestration/prefect/utils.py
> +            timezone used by all datetime functions. Defaults to "Europe/Warsaw".
Done.

2024-11-04 11:04 UTC, Rafalz13 commented on src/viadot/orchestration/prefect/utils.py
> +        """  # noqa: D205
Done.

2024-11-04 11:05 UTC, Rafalz13 commented on src/viadot/orchestration/prefect/utils.py
> +            return result  # noqa: RET504
Done.

2024-11-04 11:06 UTC, Rafalz13 commented on src/viadot/orchestration/prefect/utils.py
> +            return result  # noqa: RET504
Done

2024-11-04 11:06 UTC, Rafalz13 commented on src/viadot/orchestration/prefect/utils.py
> +        return result  # noqa: RET504
Done.

2024-11-04 11:07 UTC, Rafalz13 commented on src/viadot/orchestration/prefect/utils.py
> +        return result  # noqa: RET504
Done.

2024-11-04 11:14 UTC, Rafalz13 commented on src/viadot/orchestration/prefect/utils.py
> +        """  # noqa: D205, W505
Done.

2024-11-04 12:01 UTC, Rafalz13 commented on src/viadot/orchestration/prefect/utils.py
> +        return result  # noqa: RET504
Done.

2024-11-04 12:02 UTC, Rafalz13 commented on src/viadot/orchestration/prefect/utils.py
> +        return date  # noqa: RET504
Done.

2024-11-04 12:02 UTC, Rafalz13 commented on src/viadot/orchestration/prefect/utils.py
> +        return full_date  # noqa: RET504
Done.

2024-11-04 12:03 UTC, Rafalz13 commented on src/viadot/orchestration/prefect/utils.py
> +        return replacements  # noqa: RET504
Done.

2024-11-04 12:03 UTC, Rafalz13 commented on src/viadot/orchestration/prefect/utils.py
> +        """  # noqa: D205
Done.

2024-11-04 12:03 UTC, Rafalz13 commented on src/viadot/orchestration/prefect/utils.py
> +                return replacement  # noqa: RET504
Done.

2024-11-04 12:03 UTC, Rafalz13 commented on src/viadot/orchestration/prefect/utils.py
> +                return replacement  # noqa: RET504
Done.

2024-11-04 12:04 UTC, Rafalz13 commented on src/viadot/orchestration/prefect/utils.py
> +                return replacement  # noqa: RET504
Done.

2024-11-04 12:42 UTC, Rafalz13 commented on tests/unit/orchestration/prefect/test_utils.py
> +    )
"Skip all tests in a file when a required extra is not installed."

2024-11-04 13:30 UTC, Rafalz13 commented on src/viadot/orchestration/prefect/utils.py
> +                replacement = eval(match_no_symbols)  # noqa: S307
`literal_eval` doesn't work properly because we need to pass more complex expressions here.

2024-11-05 08:25 UTC, trymzet commented on tests/unit/orchestration/prefect/test_utils.py
> +    )
But this code doesn't seem to require a new dependency, and I don't see any extra added in pyproject.toml?

2024-11-05 09:05 UTC, Rafalz13 commented on tests/unit/orchestration/prefect/test_utils.py
> +    )
I hope this can be removed. I'm going to do so.

2024-11-05 09:05 UTC, trymzet commented on src/viadot/orchestration/prefect/utils.py
> +                replacement = eval(match_no_symbols)  # noqa: S307
Ok, then how is this code going to be used? Because this is easily exploitable by providing eg. `<<exec('import shutil;shutil.rmtree("/home")')>>` as the date string. That's why there's a security warning from the linter.

2024-11-05 09:54 UTC, trymzet commented on tests/unit/orchestration/prefect/test_utils.py
> +    )
Extra is another word for optional dependency. I think you need to understand what these are to understand what this code is doing - see eg. https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#dependencies-and-requirements

2024-11-06 12:14 UTC, Rafalz13 commented on src/viadot/orchestration/prefect/utils.py
> +                replacement = eval(match_no_symbols)  # noqa: S307
Added regex -> [90731a1](https://github.com/dyvenia/viadot/pull/1093/commits/90731a19f7d30f10ac342ed94531fecb0a083014)

2024-11-06 13:55 UTC, trymzet approved these changes

2024-11-06 14:09 UTC, merged