UK Carbon Instensity Statistics (stats) to a excel file
dyvenia/viadot pull request #27
Opened 2021-05-14 18:53 UTC by AdamSulek

StatsToExcel class may propably write inside StatsToCSV but i create another file. 
Also not sure if to_excel function should be in  Source instead of UKCarbonIntensity class but in my case it works. 
Jupyter dose not open excel file so after revoke run(), please open xlsx file from parent directory.

2021-05-15 03:42 UTC, acivitillo commented
@AdamSulek the code looks good, can you also add a unit test here: https://github.com/dyvenia/viadot/blob/main/tests/prefect/test_uk_carbon_intensity_tasks.py

You should also run those tests, try `pytest test_uk_carbon_intensity_tasks.py`. If this doesn't work it's the right time to start using docker as viadot's docker has the correct libraries. Check "Running Tests" in the README file of viadot.

The code is a bit weird, you need to understand what a `fixture` is (line 9). You can ping me today, @Trymzet is an expert of fixtures and he is working with me today too.

2021-05-15 17:46 UTC, AdamSulek commented
Tests for StatsToCSV and StatsToExcel class. 
Documentation for using StatsToCSV and StatsToExcel class. 
Library for StatsToCSV and StatsToExcel class.

2021-05-16 06:24 UTC, acivitillo requested changes
@AdamSulek thanks for the PR, it looks good, I have only requested 2 additional changes. If you update your PR I can approve it and you have your first commit in /main!

2021-05-16 06:24 UTC, acivitillo commented on .config/credentials.json.template
> -{
@AdamSulek your commit is eliminating this file from the `main` branch. Please uncommit this file from your PR (or just add it back and commit again). In general be careful using `git commit add .` as it adds all your repo changes, it is better to add folders or files `git commit add tests`

2021-05-16 06:24 UTC, acivitillo commented on tests/prefect/test_uk_carbon_intensity_tasks.py
> +    excel_file2 = excel_file.active
you don't need `excel_file2`, we normally don't use names like `var1`. You should be able to do `excel_file = load_workbook(TEST_FILE_PATH_EXCEL).active`

2021-05-16 14:34 UTC, AdamSulek commented
Adding a config.json.template 
Changing test for excel file with uk_carbon_intensity with excel file content

2021-05-17 03:18 UTC, merged