✨ Added bcp error handling
dyvenia/viadot pull request #391
Opened 2022-04-28 11:19 UTC by angelika233

## Summary
Added error log file to`BCPTask` and parameter  `on_error` parameter in `BCPTask` that tells what to do if bcp error occurs. added both options to `ADLSToAzureSQL`.

## Importance
 Added bcp error handling

## Checklist

This PR:

- [x] adds new tests (if appropriate)
- [x] updates docstrings for any new functions or function arguments (if appropriate)
- [x] updates `CHANGELOG.md` with a summary of the changes

2022-05-06 08:06 UTC, winiar93 commented on tests/integration/tasks/test_bcp.py
>  from viadot.tasks import BCPTask
Move absolute imports on top and after that relatives ones.

2022-05-06 08:18 UTC, winiar93 commented on viadot/tasks/bcp.py
> +        f = f.readlines()
change variable (f) name to describes its purpose

2022-06-22 11:44 UTC, Trymzet requested changes
Some minor changes requested, otherwise looks good.

2022-06-22 11:44 UTC, Trymzet commented on viadot/flows/adls_to_azure_sql.py
> +        on_error: Literal["skip", "fail"] = "skip",
This flow contains multiple tasks, so IMO it would be better to be more precise with eg. `on_bcp_error`.

2022-06-22 11:44 UTC, Trymzet commented on viadot/tasks/bcp.py
> +def parse_logs(log_file_name: str):
This should be file path not name.

2022-06-22 11:44 UTC, Trymzet commented on viadot/tasks/bcp.py
> +        - error_log_file (string, optional): Full path of an error file. Defaults to "log_file.log".
I would name it `error_log_file_path` to be clear

2022-06-22 11:44 UTC, Trymzet commented on viadot/flows/adls_to_azure_sql.py
> +            error_log_file=self.name.replace(" ", "_") + ".log",
Should be renamed as per comment in `bcp.py`.

2022-06-22 11:44 UTC, Trymzet commented on CHANGELOG.md
> +- Added `error_log_file` parameter in `BCPTask` that enables setting name of errors logs file
Should be renamed as per comment in bcp.py.

2022-06-22 11:44 UTC, Trymzet commented on CHANGELOG.md
> +- Added `on_error` parameter in `BCPTask` that tells what to do if bcp error occurs.
Should be renamed as per comment in the flow file.

2022-06-23 10:53 UTC, Trymzet approved these changes
Looks good :)

2022-06-23 10:56 UTC, merged