Handling POST in utils
dyvenia/viadot pull request #429
Opened 2022-06-13 09:15 UTC by angelika233

## Summary
Added handling POST requests in `handle_api_response()` and added it to `Epicor` source

## Importance
`Epicor` can use function from `utils.py`  

## Checklist

This PR:

- [ ] adds new tests (if appropriate)
- [x] updates docstrings for any new functions or function arguments (if appropriate)
- [x] updates `CHANGELOG.md` with a summary of the changes

2022-06-21 09:25 UTC, lzuchowska commented on viadot/sources/epicor.py
> +        response = handle_api_response(url=url, headers=headers, method="post")
Let's keep the convention for names of HTTP methods and capitalize them:
`get` -> `GET`
`post` -> `POST`

2022-06-21 09:25 UTC, lzuchowska commented on viadot/utils.py
> +        method (Literal ["get", "post"], optional): REST API medthod to use. Defaults to "get".
Typo:
`REST API medthod`

2022-06-21 10:49 UTC, lzuchowska requested changes
Please update the string and fix typo.

2022-06-22 08:17 UTC, lzuchowska approved these changes
Looks fine to me

2022-06-22 14:17 UTC, Trymzet requested changes
Micro changes only

2022-06-22 14:17 UTC, Trymzet commented on viadot/utils.py
> +            )
You can use `session.request(method=method)`, then you don't need this big elif.

2022-06-22 14:17 UTC, Trymzet commented on viadot/utils.py
> +        body (str, optional): Data to send using post method. Defaults to None.
I think HTTP methods are capitalized by convention, so it should be "using POST method".

2022-06-22 14:17 UTC, Trymzet commented on viadot/utils.py
> +        ValueError: raises when 'method' parameter value is unavailable
I would say "hasn't been specified" rather than "is unavailable".

2022-06-23 10:29 UTC, Trymzet approved these changes
Looks good :)

2022-06-23 10:33 UTC, merged