✨ Added query option to `DuckDBToSQLServer`
dyvenia/viadot pull request #433
Opened 2022-06-15 09:28 UTC by angelika233

## Summary
Added `duckdb_query` parameter to `DuckDBToSQLServer` flow

## Importance
User can specify query to filter the data e.g using WHERE clause

## Checklist

This PR:

- [x] adds new tests (if appropriate)
- [x] updates docstrings for any new functions or function arguments (if appropriate)
- [x] updates `CHANGELOG.md` with a summary of the changes

2022-06-22 12:00 UTC, Trymzet requested changes
Minor comments

2022-06-23 11:11 UTC, Trymzet commented
Need to double check the schema exists test before moving on

2022-08-30 13:23 UTC, Trymzet requested changes
Just need to remove the prints

2022-08-30 14:14 UTC, Trymzet commented on tests/integration/flows/test_duckdb_to_sql_server.py
> +    assert not duckdb._check_if_schema_exists(DUCKDB_SCHEMA)
@angelika233 I forgot, was this resolved?

2022-08-31 08:23 UTC, angelika233 commented on tests/integration/flows/test_duckdb_to_sql_server.py
> +    assert not duckdb._check_if_schema_exists(DUCKDB_SCHEMA)
If I remember correctly @winiar93 fixed this in one of his PR

2022-08-31 13:35 UTC, Trymzet commented on tests/integration/flows/test_duckdb_to_sql_server.py
> +    assert not duckdb._check_if_schema_exists(DUCKDB_SCHEMA)
I don't see it anywhere, can you remove this test and create an issue to fix it?

2022-08-31 15:27 UTC, Trymzet approved these changes
Looks good

2022-08-31 15:28 UTC, merged