Prefect logs
dyvenia/viadot pull request #506
Opened 2022-09-01 11:53 UTC by gwieloch

## Summary

Extended API query and added it as a flow parameter for easier modifications in the future.

## Importance

It gives full image of prefect logs without losing any data

## Checklist

This PR:

- [ ] adds new tests (if appropriate)
- [x ] updates docstrings for any new functions or function arguments (if appropriate)
- [x ] updates `CHANGELOG.md` with a summary of the changes

2022-09-05 07:01 UTC, Rafalz13 requested changes
Do the tests need updating? I can see the changed code, but I cannot see the tests.

2022-09-05 14:05 UTC, gwieloch commented on viadot/flows/prefect_logs.py
>          scheduled_start_time: str = "yesterday",
I added in dccstrings:
scheduled_start_time (str, optional): A parameter passed to the Prefect API query. Set as 'yesterday' or date in format ex. '2022-01-01'. Defaults to 'yesterday'.

2022-09-05 14:06 UTC, gwieloch commented on viadot/flows/prefect_logs.py
> +        except:
I want to pass everything without raising an error :D

2022-09-06 09:27 UTC, Rafalz13 approved these changes

2022-09-06 10:02 UTC, merged