Sftp connector
dyvenia/viadot pull request #519
Opened 2022-09-21 08:08 UTC by winiar93

## Summary
Added source and task class for downloading data from SFTP  server.

## Importance

## Checklist

This PR:

- [X] adds new tests (if appropriate)
- [X] updates docstrings for any new functions or function arguments (if appropriate)
- [X] updates `CHANGELOG.md` with a summary of the changes

2022-09-21 14:24 UTC, Rafalz13 requested changes
I am not sure that the `..ToADLS` and `..ToSQL` flows should be in the same file.
Cosmetic changes.

2022-09-21 14:24 UTC, Rafalz13 commented on viadot/sources/sftp.py
> +    def process_defaultdict(self, defaultdict: any = None):
Add return type.

2022-09-21 14:24 UTC, Rafalz13 commented on viadot/sources/sftp.py
> +            defaultdict (any): defaultdict of recursive files.
Add  `, optional` and `Defaults to None.`

2022-09-21 14:24 UTC, Rafalz13 commented on tests/integration/test_sftp.py
> +        "Country__Context30##exported.tsv",
Is `tsv` some file extension or mistake?

2022-09-21 15:20 UTC, winiar93 commented on viadot/tasks/sftp.py
> +        logger.info("Succefully downloaded file from SFTP server.")
paramiko should handle error

2022-09-22 06:50 UTC, Rafalz13 approved these changes

2022-09-22 06:50 UTC, Rafalz13 commented on viadot/flows/sftp_operations.py
> +            file_name (str, optional): File name for local file. Defaults to False.
according to __init__()-> `Defaults to None`

2022-09-22 06:53 UTC, Rafalz13 commented on viadot/flows/sftp_operations.py
> +            file_name (str, optional): File name for local file. Defaults to False.
+ Add flow_toADLS to tasks/init

2022-09-23 11:48 UTC, merged