Outlook msg fix
dyvenia/viadot pull request #570
Opened 2022-11-29 15:17 UTC by winiar93

## Summary
Workaround that solves outlook messages extraction issue.

## Importance

## Checklist

This PR:

- [X] adds new tests (if appropriate)
- [X] updates docstrings for any new functions or function arguments (if appropriate)
- [X] updates `CHANGELOG.md` with a summary of the changes

2022-12-01 08:33 UTC, angelika233 requested changes
small suggestions

2022-12-01 08:33 UTC, angelika233 commented on viadot/sources/outlook.py
> +        self.mailbox_folders = mailbox_folders
You can add check if mailbox_folders is in allowed values

2022-12-01 08:33 UTC, angelika233 commented on viadot/sources/outlook.py
>              pd.DataFrame: the DataFrame with time range
Add dot at the end of the sentence

2022-12-01 08:33 UTC, angelika233 commented on viadot/sources/outlook.py
> +                    date_time_string = date_time_str[0:19]
Maybe change the name of variable. It's okay, but it's almost the same as `date_time_str`. I would suggest sth like `date_time_stripped` or `date_time_trimmed`.

2022-12-01 08:33 UTC, angelika233 commented on viadot/sources/outlook.py
> +                            reciver_list = fetched.get("toRecipients")
Small suggestion: maybe `recivers_list` would be better?

2022-12-12 09:53 UTC, Rafalz13 requested changes

2022-12-12 09:53 UTC, Rafalz13 commented on viadot/sources/outlook.py
> +            request_retries (int): How many times retries to authorizate. Defaults to 10.
Add optional - (int, `optional`)

2022-12-12 09:53 UTC, Rafalz13 commented on viadot/sources/outlook.py
> +                            print("KeyError : " + str(e))
replace `print` with `logger`

2022-12-12 09:53 UTC, Rafalz13 commented on viadot/sources/outlook.py
>              DEFAULT_CREDENTIALS = local_config["OUTLOOK"]
you can change the authentication method. Use `credentials_loader`.

2022-12-12 14:27 UTC, Rafalz13 approved these changes

2022-12-12 14:29 UTC, merged