Genesys validate_df
dyvenia/viadot pull request #782
Opened 2023-10-25 14:18 UTC by angelika233

## Summary
Added new parameter to flow and task

## Importance
data validation

## Checklist

This PR:
- [x] follows the guidelines laid out in `CONTRIBUTING.md`
- [ ] links relevant issue(s)
- [ ] adds/updates tests (if appropriate)
- [x] adds/updates docstrings (if appropriate)
- [ ] adds an entry in `CHANGELOG.md`

2023-10-25 15:13 UTC, Diego-H-S requested changes
Please, have a look at the two comments and let me know if you have doubts.

2023-10-26 06:44 UTC, angelika233 commented on viadot/tasks/genesys.py
>              List[str]: List of file names.
Done

2023-10-26 06:46 UTC, angelika233 commented on viadot/tasks/genesys.py
> +            if validate_df_dict:
Thanks for the suggestion! For now, I won't be changing it because this if statement format is used in every flow that uses validate_df

2023-10-26 10:08 UTC, Diego-H-S approved these changes
As I told Angelika, applying this function to some endpoints in Genesys, is quite tricky and might make the flow fail.
I'm going to approve it because if nothing is passed, it can't break the flow, but I rather recommend before changing any flow, contacting the owner and asking first.

2023-10-26 11:08 UTC, merged