Sharepoint list to csv
dyvenia/viadot pull request #823
Opened 2023-11-29 12:48 UTC by cgildenia

## Summary

- Merged `path` and `adls_file_name` arguments into `file_name` in SharepointListToADLS class.
- Added to_csv functionality to SharepointListToADLS.

## Checklist

This PR:
- [ ] follows the guidelines laid out in `CONTRIBUTING.md`
- [ ] links relevant issue(s)
- [ ] adds/updates tests (if appropriate)
- [ ] adds/updates docstrings (if appropriate)
- [ ] adds an entry in `CHANGELOG.md`

2023-11-30 15:44 UTC, Rafalz13 reviewed
Look good. Please check tests for that and add if possible as we have new options for connector and output.

2023-12-04 13:31 UTC, marcinpurtak requested changes

2023-12-04 15:12 UTC, marcinpurtak approved these changes
All good

2023-12-04 16:12 UTC, Rafalz13 approved these changes

2023-12-05 14:28 UTC, merged