Modified `if_empty` logic in `ADLSToAzureSQL`
dyvenia/viadot pull request #833
Opened 2023-12-12 17:05 UTC by burzekj

## Summary
Added new logic for if_empty param in ADLSToAzureSQL flow

## Importance

## Checklist

This PR:
- [x] follows the guidelines laid out in `CONTRIBUTING.md`
- [ ] links relevant issue(s)
- [ ] adds/updates tests (if appropriate)
- [x] adds/updates docstrings (if appropriate)
- [x] adds an entry in `CHANGELOG.md`

2023-12-13 09:59 UTC, marcinpurtak requested changes

2023-12-13 09:59 UTC, marcinpurtak commented on viadot/flows/adls_to_azure_sql.py
> +            if_empty (str, optional): What to do if the loaded DataFrame is empty. Defaults to "skip".
```suggestion
            if_empty (str, optional): What to do if the loaded DataFrame is empty. Defaults to "skip" which acts like ignore this setting.
```

2023-12-13 12:02 UTC, marcinpurtak approved these changes

2023-12-19 15:25 UTC, Rafalz13 approved these changes

2023-12-22 13:08 UTC, merged