Duckdb connectors
dyvenia/viadot pull request #945
Opened 2024-07-12 09:25 UTC by angelika233

## Summary
New connectors related to duckdb
Changed location of tasks utils file because it's prefect related

## Importance
new connectors
clenup

## Checklist

This PR:
- [x] follows the guidelines laid out in `CONTRIBUTING.md`
- [ ] links relevant issue(s)
- [x] adds/updates tests (if appropriate)
- [x] adds/updates docstrings (if appropriate)
- [x] adds an entry in `CHANGELOG.md`

2024-07-15 14:36 UTC, trymzet requested changes
Most of feedback is minor so added as suggestions so that it can be quickly applied.

2024-07-15 14:36 UTC, trymzet commented on src/viadot/sources/duckdb.py
> +        Drop a table.
```suggestion
    def drop_table(self, table: str, schema: str | None = None) -> bool:
        """Drop a table.
```

2024-07-15 14:36 UTC, trymzet commented on src/viadot/sources/duckdb.py
> +        This is a thin wraper around DuckDB.run_query() which logs to the operation.
```suggestion
        A thin wrapper around DuckDB.run_query(), with additional logs.
```

2024-07-15 14:36 UTC, trymzet commented on src/viadot/sources/duckdb.py
> +            Defaults to None.
```suggestion
            schema (str, optional): The schema where the table is located. Defaults to
                None.
```

2024-07-15 14:36 UTC, trymzet commented on src/viadot/sources/duckdb.py
> +        if schema == self.DEFAULT_SCHEMA:
```suggestion
        if schema == DuckDB.DEFAULT_SCHEMA:
```

2024-07-15 14:36 UTC, trymzet commented on src/viadot/sources/duckdb.py
> +            if_exists (Literal[, optional): What to do if the table already exists. Defaults to "fail".
Most of them are self explanatory, but it would be useful to document the difference between "replace" and "delete" in the docstring.

2024-07-15 14:36 UTC, trymzet commented on tests/viadot_tests/unit/test_duckdb.py
> +    # if exists = 'delete' deletes data and then inserts new one
This info should be in the function's docstring

2024-07-16 06:28 UTC, angelika233 commented on src/viadot/orchestration/prefect/flows/duckdb_to_sql_server.py
> +    csv = df_to_csv(df=df, path=local_path)
Added task for removing this ;)

2024-07-16 11:41 UTC, trymzet approved these changes

2024-07-16 11:41 UTC, merged